// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.chaoslabgames.packet;

public interface JoinOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.Join)
    com.google.protobuf.MessageOrBuilder {
}
