// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.chaoslabgames.packet;

public interface LoginRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.LoginResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   */
  long getId();
}
