// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.chaoslabgames.packet;

public interface LoginOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.Login)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string name = 1;</code>
   */
  boolean hasName();
  /**
   * <code>required string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>required string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>required string pass = 2;</code>
   */
  boolean hasPass();
  /**
   * <code>required string pass = 2;</code>
   */
  java.lang.String getPass();
  /**
   * <code>required string pass = 2;</code>
   */
  com.google.protobuf.ByteString
      getPassBytes();
}
