// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.chaoslabgames.packet;

/**
 * Protobuf type {@code com.chaoslabgames.packet.Move}
 */
public final class Move extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.chaoslabgames.packet.Move)
    MoveOrBuilder {
  // Use Move.newBuilder() to construct.
  private Move(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private Move(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final Move defaultInstance;
  public static Move getDefaultInstance() {
    return defaultInstance;
  }

  public Move getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private Move(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              point_ = new java.util.ArrayList<com.chaoslabgames.packet.Point>();
              mutable_bitField0_ |= 0x00000001;
            }
            point_.add(input.readMessage(com.chaoslabgames.packet.Point.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        point_ = java.util.Collections.unmodifiableList(point_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_Move_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_Move_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chaoslabgames.packet.Move.class, com.chaoslabgames.packet.Move.Builder.class);
  }

  public static com.google.protobuf.Parser<Move> PARSER =
      new com.google.protobuf.AbstractParser<Move>() {
    public Move parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Move(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<Move> getParserForType() {
    return PARSER;
  }

  public static final int POINT_FIELD_NUMBER = 1;
  private java.util.List<com.chaoslabgames.packet.Point> point_;
  /**
   * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
   */
  public java.util.List<com.chaoslabgames.packet.Point> getPointList() {
    return point_;
  }
  /**
   * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
   */
  public java.util.List<? extends com.chaoslabgames.packet.PointOrBuilder> 
      getPointOrBuilderList() {
    return point_;
  }
  /**
   * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
   */
  public int getPointCount() {
    return point_.size();
  }
  /**
   * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
   */
  public com.chaoslabgames.packet.Point getPoint(int index) {
    return point_.get(index);
  }
  /**
   * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
   */
  public com.chaoslabgames.packet.PointOrBuilder getPointOrBuilder(
      int index) {
    return point_.get(index);
  }

  private void initFields() {
    point_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getPointCount(); i++) {
      if (!getPoint(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    for (int i = 0; i < point_.size(); i++) {
      output.writeMessage(1, point_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < point_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, point_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.chaoslabgames.packet.Move parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.Move parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.Move parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.Move parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.Move parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.Move parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.Move parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.chaoslabgames.packet.Move parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.Move parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.Move parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.chaoslabgames.packet.Move prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chaoslabgames.packet.Move}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chaoslabgames.packet.Move)
      com.chaoslabgames.packet.MoveOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_Move_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_Move_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chaoslabgames.packet.Move.class, com.chaoslabgames.packet.Move.Builder.class);
    }

    // Construct using com.chaoslabgames.packet.Move.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        getPointFieldBuilder();
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      if (pointBuilder_ == null) {
        point_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        pointBuilder_.clear();
      }
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_Move_descriptor;
    }

    public com.chaoslabgames.packet.Move getDefaultInstanceForType() {
      return com.chaoslabgames.packet.Move.getDefaultInstance();
    }

    public com.chaoslabgames.packet.Move build() {
      com.chaoslabgames.packet.Move result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.chaoslabgames.packet.Move buildPartial() {
      com.chaoslabgames.packet.Move result = new com.chaoslabgames.packet.Move(this);
      int from_bitField0_ = bitField0_;
      if (pointBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          point_ = java.util.Collections.unmodifiableList(point_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.point_ = point_;
      } else {
        result.point_ = pointBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chaoslabgames.packet.Move) {
        return mergeFrom((com.chaoslabgames.packet.Move)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chaoslabgames.packet.Move other) {
      if (other == com.chaoslabgames.packet.Move.getDefaultInstance()) return this;
      if (pointBuilder_ == null) {
        if (!other.point_.isEmpty()) {
          if (point_.isEmpty()) {
            point_ = other.point_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePointIsMutable();
            point_.addAll(other.point_);
          }
          onChanged();
        }
      } else {
        if (!other.point_.isEmpty()) {
          if (pointBuilder_.isEmpty()) {
            pointBuilder_.dispose();
            pointBuilder_ = null;
            point_ = other.point_;
            bitField0_ = (bitField0_ & ~0x00000001);
            pointBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getPointFieldBuilder() : null;
          } else {
            pointBuilder_.addAllMessages(other.point_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.chaoslabgames.packet.Move parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.chaoslabgames.packet.Move) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.chaoslabgames.packet.Point> point_ =
      java.util.Collections.emptyList();
    private void ensurePointIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        point_ = new java.util.ArrayList<com.chaoslabgames.packet.Point>(point_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.chaoslabgames.packet.Point, com.chaoslabgames.packet.Point.Builder, com.chaoslabgames.packet.PointOrBuilder> pointBuilder_;

    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public java.util.List<com.chaoslabgames.packet.Point> getPointList() {
      if (pointBuilder_ == null) {
        return java.util.Collections.unmodifiableList(point_);
      } else {
        return pointBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public int getPointCount() {
      if (pointBuilder_ == null) {
        return point_.size();
      } else {
        return pointBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public com.chaoslabgames.packet.Point getPoint(int index) {
      if (pointBuilder_ == null) {
        return point_.get(index);
      } else {
        return pointBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder setPoint(
        int index, com.chaoslabgames.packet.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.set(index, value);
        onChanged();
      } else {
        pointBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder setPoint(
        int index, com.chaoslabgames.packet.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.set(index, builderForValue.build());
        onChanged();
      } else {
        pointBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder addPoint(com.chaoslabgames.packet.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.add(value);
        onChanged();
      } else {
        pointBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder addPoint(
        int index, com.chaoslabgames.packet.Point value) {
      if (pointBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.add(index, value);
        onChanged();
      } else {
        pointBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder addPoint(
        com.chaoslabgames.packet.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.add(builderForValue.build());
        onChanged();
      } else {
        pointBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder addPoint(
        int index, com.chaoslabgames.packet.Point.Builder builderForValue) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.add(index, builderForValue.build());
        onChanged();
      } else {
        pointBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder addAllPoint(
        java.lang.Iterable<? extends com.chaoslabgames.packet.Point> values) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, point_);
        onChanged();
      } else {
        pointBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder clearPoint() {
      if (pointBuilder_ == null) {
        point_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        pointBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public Builder removePoint(int index) {
      if (pointBuilder_ == null) {
        ensurePointIsMutable();
        point_.remove(index);
        onChanged();
      } else {
        pointBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public com.chaoslabgames.packet.Point.Builder getPointBuilder(
        int index) {
      return getPointFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public com.chaoslabgames.packet.PointOrBuilder getPointOrBuilder(
        int index) {
      if (pointBuilder_ == null) {
        return point_.get(index);  } else {
        return pointBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public java.util.List<? extends com.chaoslabgames.packet.PointOrBuilder> 
         getPointOrBuilderList() {
      if (pointBuilder_ != null) {
        return pointBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(point_);
      }
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public com.chaoslabgames.packet.Point.Builder addPointBuilder() {
      return getPointFieldBuilder().addBuilder(
          com.chaoslabgames.packet.Point.getDefaultInstance());
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public com.chaoslabgames.packet.Point.Builder addPointBuilder(
        int index) {
      return getPointFieldBuilder().addBuilder(
          index, com.chaoslabgames.packet.Point.getDefaultInstance());
    }
    /**
     * <code>repeated .com.chaoslabgames.packet.Point point = 1;</code>
     */
    public java.util.List<com.chaoslabgames.packet.Point.Builder> 
         getPointBuilderList() {
      return getPointFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.chaoslabgames.packet.Point, com.chaoslabgames.packet.Point.Builder, com.chaoslabgames.packet.PointOrBuilder> 
        getPointFieldBuilder() {
      if (pointBuilder_ == null) {
        pointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.chaoslabgames.packet.Point, com.chaoslabgames.packet.Point.Builder, com.chaoslabgames.packet.PointOrBuilder>(
                point_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        point_ = null;
      }
      return pointBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:com.chaoslabgames.packet.Move)
  }

  static {
    defaultInstance = new Move(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.chaoslabgames.packet.Move)
}

