// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.chaoslabgames.packet;

/**
 * Protobuf type {@code com.chaoslabgames.packet.PacketMSG}
 */
public final class PacketMSG extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:com.chaoslabgames.packet.PacketMSG)
    PacketMSGOrBuilder {
  // Use PacketMSG.newBuilder() to construct.
  private PacketMSG(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private PacketMSG(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final PacketMSG defaultInstance;
  public static PacketMSG getDefaultInstance() {
    return defaultInstance;
  }

  public PacketMSG getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private PacketMSG(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            ping_ = input.readBool();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            type_ = input.readInt32();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            data_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_PacketMSG_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_PacketMSG_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.chaoslabgames.packet.PacketMSG.class, com.chaoslabgames.packet.PacketMSG.Builder.class);
  }

  public static com.google.protobuf.Parser<PacketMSG> PARSER =
      new com.google.protobuf.AbstractParser<PacketMSG>() {
    public PacketMSG parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PacketMSG(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<PacketMSG> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  public static final int PING_FIELD_NUMBER = 1;
  private boolean ping_;
  /**
   * <code>optional bool ping = 1;</code>
   *
   * <pre>
   * base
   * </pre>
   */
  public boolean hasPing() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional bool ping = 1;</code>
   *
   * <pre>
   * base
   * </pre>
   */
  public boolean getPing() {
    return ping_;
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_;
  /**
   * <code>optional int32 type = 2;</code>
   *
   * <pre>
   * data
   * </pre>
   */
  public boolean hasType() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 type = 2;</code>
   *
   * <pre>
   * data
   * </pre>
   */
  public int getType() {
    return type_;
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString data_;
  /**
   * <code>optional bytes data = 3;</code>
   */
  public boolean hasData() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional bytes data = 3;</code>
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  private void initFields() {
    ping_ = false;
    type_ = 0;
    data_ = com.google.protobuf.ByteString.EMPTY;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBool(1, ping_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, type_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, data_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, ping_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, type_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, data_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.chaoslabgames.packet.PacketMSG parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.PacketMSG parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.PacketMSG parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.chaoslabgames.packet.PacketMSG parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.chaoslabgames.packet.PacketMSG parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.PacketMSG parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.PacketMSG parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.chaoslabgames.packet.PacketMSG parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.chaoslabgames.packet.PacketMSG parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.chaoslabgames.packet.PacketMSG parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.chaoslabgames.packet.PacketMSG prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.chaoslabgames.packet.PacketMSG}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.chaoslabgames.packet.PacketMSG)
      com.chaoslabgames.packet.PacketMSGOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_PacketMSG_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_PacketMSG_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.chaoslabgames.packet.PacketMSG.class, com.chaoslabgames.packet.PacketMSG.Builder.class);
    }

    // Construct using com.chaoslabgames.packet.PacketMSG.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      ping_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = com.google.protobuf.ByteString.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.chaoslabgames.packet.Packet.internal_static_com_chaoslabgames_packet_PacketMSG_descriptor;
    }

    public com.chaoslabgames.packet.PacketMSG getDefaultInstanceForType() {
      return com.chaoslabgames.packet.PacketMSG.getDefaultInstance();
    }

    public com.chaoslabgames.packet.PacketMSG build() {
      com.chaoslabgames.packet.PacketMSG result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.chaoslabgames.packet.PacketMSG buildPartial() {
      com.chaoslabgames.packet.PacketMSG result = new com.chaoslabgames.packet.PacketMSG(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.ping_ = ping_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.type_ = type_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.data_ = data_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.chaoslabgames.packet.PacketMSG) {
        return mergeFrom((com.chaoslabgames.packet.PacketMSG)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.chaoslabgames.packet.PacketMSG other) {
      if (other == com.chaoslabgames.packet.PacketMSG.getDefaultInstance()) return this;
      if (other.hasPing()) {
        setPing(other.getPing());
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasData()) {
        setData(other.getData());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.chaoslabgames.packet.PacketMSG parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.chaoslabgames.packet.PacketMSG) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean ping_ ;
    /**
     * <code>optional bool ping = 1;</code>
     *
     * <pre>
     * base
     * </pre>
     */
    public boolean hasPing() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool ping = 1;</code>
     *
     * <pre>
     * base
     * </pre>
     */
    public boolean getPing() {
      return ping_;
    }
    /**
     * <code>optional bool ping = 1;</code>
     *
     * <pre>
     * base
     * </pre>
     */
    public Builder setPing(boolean value) {
      bitField0_ |= 0x00000001;
      ping_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool ping = 1;</code>
     *
     * <pre>
     * base
     * </pre>
     */
    public Builder clearPing() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ping_ = false;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     * data
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     * data
     * </pre>
     */
    public int getType() {
      return type_;
    }
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     * data
     * </pre>
     */
    public Builder setType(int value) {
      bitField0_ |= 0x00000002;
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 type = 2;</code>
     *
     * <pre>
     * data
     * </pre>
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes data = 3;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <code>optional bytes data = 3;</code>
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes data = 3;</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000004);
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:com.chaoslabgames.packet.PacketMSG)
  }

  static {
    defaultInstance = new PacketMSG(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:com.chaoslabgames.packet.PacketMSG)
}

