// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.chaoslabgames.packet;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_PacketMSG_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_PacketMSG_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_Login_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_Login_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_LoginResp_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_LoginResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_Join_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_Join_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_Point_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chaoslabgames_packet_Move_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_chaoslabgames_packet_Move_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\022\030com.chaoslabgames.packet" +
      "\"4\n\tPacketMSG\022\014\n\004ping\030\001 \001(\010\022\013\n\003cmd\030\002 \001(\005" +
      "\022\014\n\004data\030\003 \001(\014\"#\n\005Login\022\014\n\004name\030\001 \002(\t\022\014\n" +
      "\004pass\030\002 \002(\t\"\027\n\tLoginResp\022\n\n\002id\030\001 \002(\003\"\006\n\004" +
      "Join\")\n\005Point\022\n\n\002id\030\001 \002(\003\022\t\n\001x\030\002 \002(\005\022\t\n\001" +
      "y\030\003 \002(\005\"6\n\004Move\022.\n\005point\030\001 \003(\0132\037.com.cha" +
      "oslabgames.packet.PointB$\n\030com.chaoslabg" +
      "ames.packetB\006PacketP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chaoslabgames_packet_PacketMSG_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chaoslabgames_packet_PacketMSG_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_PacketMSG_descriptor,
        new java.lang.String[] { "Ping", "Cmd", "Data", });
    internal_static_com_chaoslabgames_packet_Login_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chaoslabgames_packet_Login_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_Login_descriptor,
        new java.lang.String[] { "Name", "Pass", });
    internal_static_com_chaoslabgames_packet_LoginResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chaoslabgames_packet_LoginResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_LoginResp_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_chaoslabgames_packet_Join_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_chaoslabgames_packet_Join_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_Join_descriptor,
        new java.lang.String[] { });
    internal_static_com_chaoslabgames_packet_Point_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_chaoslabgames_packet_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_Point_descriptor,
        new java.lang.String[] { "Id", "X", "Y", });
    internal_static_com_chaoslabgames_packet_Move_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_chaoslabgames_packet_Move_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_chaoslabgames_packet_Move_descriptor,
        new java.lang.String[] { "Point", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
