// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package com.chaoslabgames.packet;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chaoslabgames.packet.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>required int32 x = 2;</code>
   */
  boolean hasX();
  /**
   * <code>required int32 x = 2;</code>
   */
  int getX();

  /**
   * <code>required int32 y = 3;</code>
   */
  boolean hasY();
  /**
   * <code>required int32 y = 3;</code>
   */
  int getY();
}
